services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: matsustore_php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    restart: unless-stopped
